@startuml
title Sequence Diagram

actor "CRM Collaborator" as Actor
participant "SendProposalUI" as UI <<presentation>>
participant "SendProposalController" as Controller <<application>>
participant "AuthorizationService" as AuthorizationService <<auth>>
participant "ShowProposalManagementService" as ShowProposalManagementService <<application>>
participant "ShowProposal" as ShowProposal <<domain>>
participant "ShowProposalRepository" as ShowProposalRepository <<repository>>
database "Database" as Database

activate Actor

Actor -> UI: show()
    activate UI

UI -> Controller** : create()

UI -> Controller : getAllCompleteProposals()
activate Controller
Controller -> ShowProposalManagementService: getAllCompleteProposals()
activate ShowProposalManagementService
ShowProposalManagementService ->ShowProposalRepository : getAllCompleteProposals()
activate ShowProposalRepository
ShowProposalRepository ->Database:getAllCompleteProposals()
activate Database
Database --> ShowProposalRepository: List of all complete proposals
deactivate Database
ShowProposalRepository --> ShowProposalManagementService: List of all complete proposals
deactivate ShowProposalRepository
ShowProposalManagementService --> Controller: List of all complete proposals
deactivate ShowProposalManagementService
Controller -->UI: List of all complete proposals
deactivate Controller
UI --> Actor: Request a Complete show proposal
deactivate UI

Actor -> UI: Insert Show Proposal


    activate UI

        UI -> Controller : sendShowProposal(showProposal)
            activate Controller

                Controller -> AuthorizationService** : ensureAuthenticatedUserHasAnyOf()

                deactivate AuthorizationService

                Controller -> ShowProposalManagementService : sendShowProposal()
                activate ShowProposalManagementService



                Controller --> UI
            deactivate Controller
        UI --> Actor : Inform operation success
        deactivate UI
deactivate Actor

@enduml
