@startuml



package "**«Aggregate» User**" #DDDDDD {

        entity "User" as entity_user <<entity root>> {
        }


        class "UserStatus" as vObject_userStatus <<(V, #7E84F7)>> {
                            Enable
                            Disable
                }

        entity_user *--down vObject_userStatus

        entity "Admin" as entity_admin {
        }
        entity "CRM Collaborator" as entity_crmcollaborator {
        }
        entity "CRM Manager" as entity_crmManager {
        }
        entity "Show Designer" as entity_showDesigner {
        }

        entity "Drone Tech" as entity_droneTech {
                }

        entity_user <|--up entity_admin
        entity_user <|--up entity_crmcollaborator
        entity_user <|--up entity_crmManager
        entity_user <|--up entity_showDesigner
        entity_user <|--up entity_droneTech
}

class "Email" as vObject_email <<id>> <<(V, #7E84F7)>> {
        }

class "Name" as vObject_name <<(V, #7E84F7)>> {
        }

class "Password" as vObject_password <<(V, #7E84F7)>> {
        }

class "Phone Number" as vObject_phoneNumber <<(V, #7E84F7)>> {
                }

package "**«Aggregate» Employee**" #DDDDDD {

        entity "Employee" as entity_employee <<entity root>> {
        }

        class "Position" as vObject_position <<(V, #7E84F7)>> {
        }


        entity_employee *--down vObject_position
}


package "**«Aggregate» Client**" #DDDDDD {

        entity "Client" as entity_client <<entity root>> {
        }
        class "VatNumber" as vObject_vatNumber <<(V, #7E84F7)>> {
        }
        class "Address" as vObject_customerAddress <<(V, #7E84F7)>> {
        }

        class "ClientStatus" as vObject_clientStatus <<(V, #7E84F7)>> {
                    Deleted
                    Infringement
                    Created
                    Regular
                    VIP
        }

        entity_client *--down vObject_clientStatus
        entity_client *--down vObject_customerAddress
        entity_client *--down vObject_vatNumber


}

package "**«Aggregate» Drone**" #DDDDDD {

        entity "Drone" as entity_drone <<entity root>> {
        }
        class "Routine" as vObject_routine <<(V, #7E84F7)>> {
        }
        class "SerialNumber" as vObject_serialNumber <<id>> <<(V, #7E84F7)>> {
        }

        entity_drone *--down vObject_routine
        entity_drone *--down vObject_serialNumber
}



package "**«Aggregate» Figure**" #DDDDDD {

        entity "Figure" as entity_figure <<entity root>> {
        }
        class "Description" as vObject_description <<(V, #7E84F7)>> {
        }
        class "Version" as vObject_figureVersion <<(V, #7E84F7)>> {
        }

        class "DslCode" as vObject_dslCode <<(V, #7E84F7)>> {
        }

        class "Code" as vObject_code <<(V, #7E84F7)>> {
                }

        entity_figure *--down vObject_description
        entity_figure *--down vObject_figureVersion
        entity_figure *--down vObject_dslCode
        entity_figure *--down vObject_code


}

package "**«Aggregate» Catalogue**" #DDDDDD {

    entity "Catalogue" as entity_catalogue <<entity root>> {
    }


}




entity_client *--down vObject_email
entity_client *--down vObject_name
entity_client *--down vObject_password


entity_user *--down vObject_email
entity_user *--down vObject_password
entity_user *--down vObject_name
entity_user *--down vObject_phoneNumber






entity_employee *--up vObject_email
entity_employee *--left vObject_name
entity_employee *--up vObject_password
entity_employee *--down vObject_phoneNumber




entity_client --> entity_employee: "is represented by"

entity_figure --> entity_catalogue: "is in"

@enduml