@startuml

package "**«Aggregate» Client**" #DDDDDD {

        entity "Client" as entity_client <<entity root>> {
        }
        class "VatNumber" as vObject_vatNumber <<(V, #7E84F7)>> {
        }
        class "Address" as vObject_customerAddress <<(V, #7E84F7)>> {
        }
        class "Email" as vObject_email <<(V, #7E84F7)>> {
        }

        class "Name" as vObject_name <<(V, #7E84F7)>> {
        }

        class "Password" as vObject_password <<(V, #7E84F7)>> {
        }

        class "Phone Number" as vObject_phoneNumber <<(V, #7E84F7)>> {
        }



        class "ClientStatus" as vObject_clientStatus <<(V, #7E84F7)>> {
                    Deleted
                    Infringement
                    Created
                    Regular
                    VIP
        }

        entity "Representative" as entity_representative {
            }

            class "Position" as vObject_position <<(V, #7E84F7)>> {
            }

        entity_representative *--down vObject_position
        entity_client "1"<--"1..*"  entity_representative: "represents"
        entity_client *--down vObject_clientStatus
        entity_client *--down vObject_customerAddress
        entity_client *--down vObject_vatNumber
        entity_client *--down vObject_email
        entity_client *--down vObject_name
        entity_client *--down vObject_password
        entity_client *--down vObject_phoneNumber


}

package "**«Aggregate» Drone**" #DDDDDD {

        entity "Drone" as entity_drone <<entity root>> {
        }
        class "Routine" as vObject_routine <<(V, #7E84F7)>> {
        }
        class "SerialNumber" as vObject_serialNumber <<id>> <<(V, #7E84F7)>> {
        }
        class "DslCode" as vObject_dslCode <<(V, #7E84F7)>> {
        }

        class "DroneStatus" as vObject_droneStatus <<(V, #7E84F7)>> {
            Active
            Inactive
            Maintenance
            Faulty
        }

        entity "Maintenance" as entity_maintenance {
        }
        class "Date" as vObject_date <<(V, #7E84F7)>> {
        }

        entity_drone *--down vObject_droneStatus

        entity_drone "*"<-- "*" entity_maintenance: "is done on"
        entity_drone *--down vObject_dslCode
        entity_drone *--down vObject_routine
        entity_drone *--down vObject_serialNumber
        entity_maintenance *--down vObject_date
}

package "**«Aggregate» DroneModel**" #DDDDDD {

    entity "DroneModel" as entity_droneModel  <<entity root>> {
    }

}

package "**«Aggregate» ProgrammingLanguage**" #DDDDDD {

        entity "ProgrammingLanguage" as entity_programmingLanguage  <<entity root>> {
        }

}


package "**«Aggregate» ShowRequest**" #DDDDDD {

    entity "ShowRequest" as entity_showRequest  <<entity root>> {
    }


    class "RequestDate" as vObject_requestDate <<(V, #7E84F7)>> {
    }
    class "Place" as vObject_showPlace <<(V, #7E84F7)>> {
    }
    class "RequestedShowDate" as vObject_requestedShowDate <<(V, #7E84F7)>> {
    }
    class "RequestedNumberDrones" as vObject_requestedNumberDrones <<(V, #7E84F7)>> {
    }
    class "RequestedDuration" as vObject_requestedDuration <<(V, #7E84F7)>> {
    }

    class "RequestStatus" as vObject_requestStatus <<(V, #7E84F7)>> {
        Accepted
        Declined
        Pending
    }
    entity "ShowProposal" as entity_showProposal{
    }
    class "ProposedNumberDrones" as vObject_proposedNumberDrones <<(V, #7E84F7)>> {
    }
    class "ProposedDuration" as vObject_proposedDuration <<(V, #7E84F7)>> {
    }

    class "AcceptanceDate" as vObject_acceptanceDate <<(V, #7E84F7)>> {
    }

    class "ProposalStatus" as vObject_proposalStatus <<(V, #7E84F7)>> {
        Accepted
        Declined
        Pending
        Testing
    }

    entity "ShowSchedule" as entity_showSchedule  {
    }

    class "ShowDate" as vObject_showDate <<(V, #7E84F7)>> {
    }
    class "IsTested" as vObject_isTested <<(V, #7E84F7)>> {
    }

    entity "RequestedFigures" as entity_requestedFigures{
    }
    class "Sequence" as vObject_sequence <<(V, #7E84F7)>> {
    }


    entity_showRequest "1"-->"1" entity_requestedFigures: "contains"

    entity_showProposal *--down vObject_acceptanceDate
    entity_showProposal *--down vObject_proposalStatus

    entity_showRequest *--down vObject_showPlace
    entity_showRequest *--down vObject_requestedShowDate
    entity_showRequest *--down vObject_requestedNumberDrones
    entity_showRequest *--down vObject_requestedDuration
    entity_showRequest *--down vObject_requestStatus
    entity_showRequest *--down vObject_requestDate

    entity_showRequest "1"<--"1..*" entity_showProposal: "responds to"

    entity_showProposal *--down vObject_proposedDuration
    entity_showProposal *--down vObject_proposedNumberDrones

    entity_showSchedule *--down vObject_showDate
    entity_showSchedule *--down vObject_isTested

    entity_showProposal "1"<-- "1" entity_showSchedule: "comes from"

    entity_requestedFigures *--down vObject_sequence
}


package "**«Aggregate» Figure**" #DDDDDD {

        entity "Figure" as entity_figure <<entity root>> {
        }
        class "Description" as vObject_description <<(V, #7E84F7)>> {
        }
        class "Version" as vObject_figureVersion <<(V, #7E84F7)>> {
        }
        class "DslCode" as vObject_dslCode <<(V, #7E84F7)>> {
        }
        class "CreatedBy" as vObject_createdBy <<(V, #7E84F7)>> {
        }
        class "Status" as vObject_status <<(V, #7E84F7)>> {
            Public
            Exclusive
            Decommissioned
        }

        entity_figure *--down vObject_status
        entity_figure *--down vObject_createdBy
        entity_figure *--down vObject_description
        entity_figure *--down vObject_figureVersion
        entity_figure *--down vObject_dslCode

}

package "**«Aggregate» FigureType**" #DDDDDD {

        entity "FigureType" as entity_figureType  <<entity root>> {
        }

}



entity_requestedFigures "*" -->"1..*" entity_figure:"contains"

entity_drone "1..*"-->"*" entity_figure: "used in"

entity_representative "1"---up>"1..*" entity_showRequest: "requests"


entity_droneModel "*"-->"1" entity_programmingLanguage: "uses"

entity_droneModel "1"<--"*" entity_drone: "contains"


entity_figureType "1"<-- "*" entity_figure: "can be"

@enduml