@startuml

package "**«Aggregate» User**" #DDDDDD {

        entity "User" as entity_user <<entity root>> {
        }

        entity "Show Designer" as entity_showDesigner {
        }
        entity "Admin" as entity_admin {
        }
        entity "CRM Collaborator" as entity_crmcollaborator {
        }
        entity "CRM Manager" as entity_crmManager {
        }
        entity "Drone Tech" as entity_droneTech {
        }
        class "UserStatus" as vObject_userStatus <<(V, #7E84F7)>> {
            Enable
            Disable
        }


        class "Email" as vObject_email <<id>> <<(V, #7E84F7)>> {
        }

        class "Name" as vObject_name <<(V, #7E84F7)>> {
        }

        class "Password" as vObject_password <<(V, #7E84F7)>> {
        }

        class "Phone Number" as vObject_phoneNumber <<(V, #7E84F7)>> {
        }
        entity_user *--down vObject_userStatus

        entity_user <|--up entity_showDesigner
        entity_user <|--up entity_crmManager
        entity_user <|--up entity_admin
        entity_user <|--up entity_crmcollaborator
        entity_user <|--up entity_droneTech
        entity_user *--down vObject_email
        entity_user *--down vObject_password
        entity_user *--down vObject_name
        entity_user *--down vObject_phoneNumber
}




package "**«Aggregate» Client**" #DDDDDD {

        entity "Client" as entity_client <<entity root>> {
        }
        class "VatNumber" as vObject_vatNumber <<(V, #7E84F7)>> {
        }
        class "Address" as vObject_customerAddress <<(V, #7E84F7)>> {
        }
        class "Email" as vObject_email <<id>> <<(V, #7E84F7)>> {
        }

        class "Name" as vObject_name <<(V, #7E84F7)>> {
        }

        class "Password" as vObject_password <<(V, #7E84F7)>> {
        }

        class "Phone Number" as vObject_phoneNumber <<(V, #7E84F7)>> {
        }

        entity "Representative" as entity_repesentative {
        }


        class "Position" as vObject_position <<(V, #7E84F7)>> {
        }

        entity_repesentative *--down vObject_position

        class "ClientStatus" as vObject_clientStatus <<(V, #7E84F7)>> {
                    Deleted
                    Infringement
                    Created
                    Regular
                    VIP
        }

        entity_client *--down vObject_clientStatus
        entity_client *--down vObject_customerAddress
        entity_client *--down vObject_vatNumber
        entity_client *--down vObject_email
        entity_client *--down vObject_name
        entity_client *--down vObject_password
        entity_client *--down vObject_phoneNumber


}

package "**«Aggregate» Drone**" #DDDDDD {

        entity "Drone" as entity_drone <<entity root>> {
        }
        class "Routine" as vObject_routine <<(V, #7E84F7)>> {
        }
        class "SerialNumber" as vObject_serialNumber <<id>> <<(V, #7E84F7)>> {
        }
        class "Code" as vObject_code <<(V, #7E84F7)>> {
        }
        class "Model" as vObject_model <<(V, #7E84F7)>> {
        }
        class "MovementType" as vObject_movementType <<(V, #7E84F7)>> {
        }

        entity_drone *--down vObject_model
        entity_drone *--down vObject_code
        entity_drone *--down vObject_routine
        entity_drone *--down vObject_serialNumber
        entity_drone *--down vObject_movementType
}
package "**«Aggregate» DroneInventory**" #DDDDDD {

    entity "DroneInventory" as entity_droneInventory  <<entity root>> {
    }

}

package "**«Aggregate» ShowRequest**" #DDDDDD {

    entity "ShowRequest" as entity_showRequest  <<entity root>> {
    }
    entity "ShowProposal" as entity_showProposal  {
    }
    class "AcceptanceDate" as vObject_acceptanceDate <<(V, #7E84F7)>> {
    }
    class "RequestDate" as vObject_requestDate <<(V, #7E84F7)>> {
    }
    class "Place" as vObject_showPlace <<(V, #7E84F7)>> {
    }
    class "Time" as vObject_showTime <<(V, #7E84F7)>> {
    }
    class "NumberDrones" as vObject_showNumberDrones <<(V, #7E84F7)>> {
    }
    class "Duration" as vObject_showDuration <<(V, #7E84F7)>> {
    }

    entity_showRequest *--down vObject_showPlace
    entity_showRequest *--down vObject_showTime
    entity_showRequest *--down vObject_showNumberDrones
    entity_showRequest *--down vObject_showDuration

    entity_showRequest *--down vObject_requestDate
    entity_showProposal *--down vObject_acceptanceDate

}

package "**«Aggregate» Show**" #DDDDDD {


    entity "Show" as entity_show    {
    }

}

package "**«Aggregate» Simulation**" #DDDDDD {

    entity "Simulation" as entity_simulation  <<entity root>> {
    }
    class "Orchestrator" as vObject_orchestrator <<(V, #7E84F7)>> {
    }
    class "Subarea" as vObject_subarea <<(V, #7E84F7)>> {
    }

    entity_simulation*--down vObject_orchestrator
    entity_simulation*--down vObject_subarea
}


package "**«Aggregate» Figure**" #DDDDDD {

        entity "Figure" as entity_figure <<entity root>> {
        }
        class "Description" as vObject_description <<(V, #7E84F7)>> {
        }
        class "Version" as vObject_figureVersion <<(V, #7E84F7)>> {
        }

        class "Code" as vObject_code <<(V, #7E84F7)>> {
                }

        entity_figure *--down vObject_description
        entity_figure *--down vObject_figureVersion
        entity_figure *--down vObject_code

}
package "**«Aggregate» DslCode**" #DDDDDD {

    entity "DslCode" as entity_dslCode  <<entity root>> {
    }
    class "Version" as vObject_version <<(V, #7E84F7)>> {
    }
    class "Id" as vObject_id <<id>> <<(V, #7E84F7)>> {
    }
    class "FigureType" as vObject_figureType <<(V, #7E84F7)>> {
    }

    entity_dslCode *--down vObject_version
    entity_dslCode *--down vObject_id
    entity_dslCode *--down vObject_figureType
}

package "**«Aggregate» Catalogue**" #DDDDDD {

    entity "Catalogue" as entity_catalogue <<entity root>> {
    }


}






entity_drone --> entity_figure: "is used in"
entity_drone *--down entity_droneInventory

entity_client --> entity_repesentative: "is represented by"
entity_client ---up> entity_showRequest: "requests"

entity_dslCode --> entity_drone: "generates code for"

entity_figure *-- entity_dslCode
entity_figure --> entity_catalogue: "is in"

entity_catalogue <-- entity_showRequest

entity_simulation *--down entity_show
entity_user <|-- entity_repesentative

entity_client --> entity_showProposal : "accepts"
entity_showRequest <|-- entity_showProposal
entity_show <-- entity_showProposal

@enduml