@startuml
title Sequence Diagram

actor "CRM Collaborator" as Actor
participant "MarkShowProposalAction" as Action <<presentation>>
participant "MarkShowProposalUI" as UI <<presentation>>
participant "MarkShowProposalController" as Controller <<application>>
participant "ShowProposal" as ShowProposal <<domain>>
participant "ShowProposalRepository" as ShowProposalRepository <<repository>>
database "Database" as Database

activate Actor

Actor -> Action**: Wants to mark show proposal as accepted

activate Action

Action -> UI** : create
Action -> UI: show()

deactivate Action
    activate UI

UI -> Controller** : create
UI -> Controller: getAnsweredShowProposals()

    activate Controller

        Controller -> ShowProposalRepository: findByAcceptedProposals()

        activate ShowProposalRepository

        ShowProposalRepository -> Database: findByAcceptedProposals()
        activate Database

        Database --> ShowProposalRepository: List of Show Proposals Accepted by the Customer
        deactivate Database
        ShowProposalRepository --> Controller: List of Show Proposals Accepted by the Customer
        deactivate ShowProposalRepository
        Controller --> UI: List of Show Proposals Accepted by the Customer
    deactivate Controller

UI --> Actor: Show List of Show Proposals Accepted by the Customer
deactivate UI

Actor -> UI: Choose Show proposal


    activate UI

        UI -> Controller: markShowProposal(showProposal)
        activate Controller

        Controller -> ShowProposal: markShowProposal()
            activate ShowProposal

            ShowProposal --> Controller
            deactivate ShowProposal
            Controller --> UI:
        deactivate Controller
        UI --> Actor: Confirm Show Proposal was accepted

    deactivate UI
deactivate Actor

@enduml
