@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "System" as system

title System Sequence Diagram - US317

== Mark show proposal as accepted ==
activate crmCollaborator

crmCollaborator -> system : Wants to mark show proposal as accepted
activate system

system -> crmCollaborator :  Show List of Show Proposals Accepted by the Customer
deactivate system
crmCollaborator -> system : Choose Show proposal

activate system
system -> system: Mark show proposal\n  as accepted
system -> crmCollaborator : Confirm Show Proposal was accepted
deactivate system



@enduml
