@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "AddVideoProposalAction" as ACTION <<presentation>>
participant "AddVideoProposalUI" as UI <<presentation>>
participant "AddVideoController" as CTRL <<application>>
participant "AuthorizationService" as AuthorizationService <<auth>>
participant "CustomerManagementService" as CustomerManagementService <<application>>
participant "ShowProposalManagementService" as ShowProposalManagementService <<application>>
participant "CustomerDTOParser" as CustomerDTOParser <<dto>>
participant "ShowProposalDTOParser" as ShowProposalDTOParser <<dto>>
participant "ShowProposal" as ShowProposal <<domain>>
participant "CustomerRepository" as CustomerRepository <<repository>>
participant "ShowProposalRepository" as ShowProposalRepository <<repository>>
database "Database" as Database

title Sequence Diagram - US230

activate crmCollaborator

    crmCollaborator -> ACTION : Asks to add a video of simulation to a show proposal
    activate ACTION

        ACTION -> UI** : create
        ACTION -> UI : show()
        deactivate ACTION

        activate UI

        UI -> CTRL**: create
        UI -> CTRL : listCustomers()
        activate CTRL

            CTRL -> AuthorizationService** : ensureAuthenticatedUserHasAnyOf(Roles.CRM_COLLABORATOR)
            CTRL -> CustomerManagementService : findAllActiveCustomers()
            activate CustomerManagementService

                CustomerManagementService -> CustomerRepository : findByActive(true)
                activate CustomerRepository

                    CustomerRepository -> Database : findByActive(true)
                    activate Database

                        Database -> CustomerRepository : customers
                    deactivate Database

                    CustomerRepository -> CustomerManagementService : customers
                deactivate CustomerRepository

                CustomerManagementService -> CTRL : customers
            deactivate CustomerManagementService

            CTRL -> CustomerDTOParser : transformToCustomerDTOList(customers)
            activate CustomerDTOParser

                CustomerDTOParser -> CTRL : customersDTO
            deactivate CustomerDTOParser

            CTRL -> UI : customersDTO
        deactivate CTRL
        UI -> crmCollaborator : displays list of customers
    deactivate UI

    crmCollaborator -> UI : selects a customer
    activate UI

        UI -> CTRL : listShowProposals(customerDTO)
        activate CTRL

            CTRL -> CustomerDTOParser : getCustomerFromDTO(customerDTO)
            activate CustomerDTOParser

                CustomerDTOParser -> CTRL : customer
            deactivate CustomerDTOParser

            CTRL -> ShowProposalManagementService : findByPendingAndEmptyVideo(customer, status)
            activate ShowProposalManagementService

                ShowProposalManagementService -> ShowProposalRepository : findByPendingAndEmptyVideo(customer, status)
                activate ShowProposalRepository

                    ShowProposalRepository -> Database : findByPendingAndEmptyVideo(customer, status)
                    activate Database

                        Database -> ShowProposalRepository : showProposals
                    deactivate Database

                    ShowProposalRepository -> ShowProposalManagementService : showProposals
                deactivate ShowProposalRepository

                ShowProposalManagementService -> CTRL : showProposals
            deactivate ShowProposalManagementService

            CTRL -> ShowProposalDTOParser : transformToShowProposalDTOlist(showProposals)
            activate ShowProposalDTOParser

                ShowProposalDTOParser -> CTRL : showProposalsDTO
            deactivate ShowProposalDTOParser

            CTRL -> UI : showProposalsDTO
        deactivate CTRL

        UI -> crmCollaborator : displays the list of show proposal of the customer
    deactivate UI

    crmCollaborator -> UI : selects a show proposal
    activate UI

        UI -> crmCollaborator : request a video file of the simulation
    deactivate UI

    crmCollaborator -> UI : gives video file
    activate UI

        UI -> CTRL : addVideoToProposal(video, showProposalDTO)
        activate CTRL

            CTRL -> ShowProposalDTOParser : getShowProposalfromDTO(showProposalDTO)
            activate ShowProposalDTOParser

                ShowProposalDTOParser -> CTRL : showProposal
            deactivate ShowProposalDTOParser

            CTRL -> ShowProposal : addVideoToProposal(video, showProposal)
            activate ShowProposal

                ShowProposal -> CTRL : updatedShowProposal
            deactivate ShowProposal

            CTRL -> ShowProposalRepository : save(proposal)
            activate ShowProposalRepository

                ShowProposalRepository -> Database : save()
                activate Database

                    Database --> ShowProposalRepository :
                deactivate Database

                ShowProposalRepository --> CTRL :
            deactivate ShowProposalRepository

            CTRL --> UI :
        deactivate CTRL

        UI -> crmCollaborator : displays operation success
    deactivate UI

@enduml