@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "AddVideoProposalAction" as ACTION <<presentation>>
participant "AddVideoProposalUI" as UI <<presentation>>
participant "AddVideoController" as CTRL <<application>>
participant "AuthorizationService" as AuthorizationService <<auth>>
participant "CustomerManagementService" as CustomerManagementService <<application>>
participant "ShowProposalManagementService" as ShowProposalManagementService <<application>>
participant "ShowProposal" as ShowProposal <<domain>>
participant "CustomerRepository" as CustomerRepository <<repository>>
participant "ShowProposalRepository" as ShowProposalRepository <<repository>>
database "Database" as Database

title Sequence Diagram - US230

activate crmCollaborator

    crmCollaborator -> ACTION : Asks to add a video of simulation to a show proposal
    activate ACTION

        ACTION -> UI** : create
        ACTION -> UI : show()
        deactivate ACTION

        activate UI

        UI -> CTRL**: create
        UI -> CTRL : listCustomers()
        activate CTRL

            CTRL -> AuthorizationService** : ensureAuthenticatedUserHasAnyOf(Roles.CRM_COLLABORATOR)
            CTRL -> CustomerManagementService : findAllActiveCustomers()
            activate CustomerManagementService

                CustomerManagementService -> CustomerRepository : findByActive(true)
                activate CustomerRepository

                    CustomerRepository -> Database : findByActive(true)
                    activate Database

                        Database -> CustomerRepository : listOfActiveClients
                    deactivate Database

                    CustomerRepository -> CustomerManagementService : listOfActiveClients
                deactivate CustomerRepository

                CustomerManagementService -> CTRL : listOfActiveClients
            deactivate CustomerManagementService

            CTRL -> UI : listOfActiveClients
        deactivate CTRL
        UI -> crmCollaborator : displays list of customers
    deactivate UI

    crmCollaborator -> UI : selects a customer
    activate UI

        UI -> CTRL : listShowProposals(customer)
        activate CTRL

            CTRL -> ShowProposalManagementService : findByPendingAndEmptyVideo(customer, status)
            activate ShowProposalManagementService

                ShowProposalManagementService -> ShowProposalRepository : findByPendingAndEmptyVideo(customer, status)
                activate ShowProposalRepository

                    ShowProposalRepository -> Database : findByPendingAndEmptyVideo(customer, status)
                    activate Database

                        Database -> ShowProposalRepository : listOfShowProposals
                    deactivate Database

                    ShowProposalRepository -> ShowProposalManagementService : listOfShowProposals
                deactivate ShowProposalRepository

                ShowProposalManagementService -> CTRL : listOfShowProposals
            deactivate ShowProposalManagementService

            CTRL -> UI : listOfShowProposals
        deactivate CTRL

        UI -> crmCollaborator : displays the list of show proposal of the customer
    deactivate UI

    crmCollaborator -> UI : selects a show proposal
    activate UI

        UI -> crmCollaborator : request a video file of the simulation
    deactivate UI

    crmCollaborator -> UI : gives video file
    activate UI

        UI -> CTRL : addVideoToProposal(video, showProposal)
        activate CTRL

            CTRL -> ShowProposal : addVideoToProposal(video, showProposal)
            activate ShowProposal

                ShowProposal -> CTRL : updatedShowProposal
            deactivate ShowProposal

            CTRL -> ShowProposalRepository : save(proposal)
            activate ShowProposalRepository

                ShowProposalRepository -> Database : save()
                activate Database

                    Database --> ShowProposalRepository :
                deactivate Database

                ShowProposalRepository --> CTRL :
            deactivate ShowProposalRepository

            CTRL --> UI :
        deactivate CTRL

        UI -> crmCollaborator : displays operation success
    deactivate UI

@enduml