@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Administrator" as admin
participant "System" as system

title System Sequence Diagram - US211

== Register users ==
activate admin

admin -> system : Register User
activate system

system -> admin : Request User Information ("Name, Email, \nRole, Password, Phone Number")
deactivate system
admin -> system : Provide User Information

activate system

system -> admin : Confirm User Register
deactivate system



@enduml
