@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "System" as system

title System Sequence Diagram - US230

 == Register a show request ==
 activate crmCollaborator

     crmCollaborator -> system : Ask to register a show request
     activate system

         system -> crmCollaborator : request data(location, date, duration, number of drones of the show)
     deactivate system

     crmCollaborator -> system : types requested date
     activate system

         system -> crmCollaborator : Shows the list of the clients representatives
     deactivate system

     crmCollaborator -> system : selects a representative
     activate system

         system -> crmCollaborator : disables the costumer representative and displays operation success
     deactivate system

 @enduml