@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "System" as system

title System Sequence Diagram - US230

 == Register a show request ==
 activate crmCollaborator

     crmCollaborator -> system : Ask to register a show request
     activate system

         system -> crmCollaborator : request data(location, date, duration, number of drones of the show)
     deactivate system

     crmCollaborator -> system : types requested data
     activate system

         loop While user wants to create figures
         system -> crmCollaborator : displays the list of the current figures in the catalogue \nand asks if the user wants to create a new figure
     deactivate system

     crmCollaborator -> system : answers with yes or no
     activate system

         alt User wants to create a new figure
            system -> crmCollaborator : request figure data
            crmCollaborator -> system : types figure data
         else User does not want to create a figure

         end
         end

         loop While user wants to add figures to the show
         system -> crmCollaborator : displays the list of figures and asks the user to select \nthe figures according with the desired order
     deactivate system
     alt User selects a figure for the show
     crmCollaborator -> system : selects desired figure
     activate system

        system -> crmCollaborator : displays the sequence figures in the show
        else User does not want to select more figures to the show
        end
        end

        system -> crmCollaborator : displays operation success
     deactivate system
 @enduml