@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "System" as system

title System Sequence Diagram - US224

== Disable a costumer representative ==
activate crmCollaborator

    crmCollaborator -> system : Ask to disable a costumer representative
    activate system

        system -> crmCollaborator : Shows list of clients
    deactivate system

    crmCollaborator -> system : Selects a client
    activate system

        system -> crmCollaborator : Shows the list of the clients representatives
    deactivate system

    crmCollaborator -> system : selects a representative
    activate system

        system -> crmCollaborator : disables the costumer representative and displays operation success
    deactivate system

@enduml
