@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Manager" as crmManager
participant "System" as system

title System Sequence Diagram - US233

== Disable a costumer representative ==
activate crmManager

    crmManager -> system : Ask to disable a costumer representative
    activate system

        system -> crmManager : Shows list of clients
    deactivate system

    crmManager -> system : Selects a client
    activate system

        system -> crmManager : Shows the list of the clients representatives
    deactivate system

    crmManager -> system : selects a representative
    activate system

        system -> crmManager : disables the costumer representative and displays operation success
    deactivate system

@enduml
