@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "System" as system

title System Sequence Diagram - Add figures to a proposal

== Add figures to a proposal ==
activate crmCollaborator

crmCollaborator -> system : Wants to add figures to a show proposal
activate system
system --> crmCollaborator : Shows list of pending show proposals
deactivate system

crmCollaborator -> system : Selects a show proposal
activate system
system --> crmCollaborator : Do you want to create a new figure sequence? (y/n)
deactivate system

crmCollaborator -> system : Responds (y/n)
activate system

alt User chooses 'y'
    loop While user wants to add figures
        system --> crmCollaborator : Shows list of figures
        deactivate system

        crmCollaborator -> system : Selects figure(s) to add
        activate system
    end
else User chooses 'n'
    system --> crmCollaborator : Assign figure to a drone model
crmCollaborator -> system : Selects drone model
end

system --> crmCollaborator : Confirmation of operation
deactivate system

@enduml