@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Manager" as crmManager
participant "System" as system

title System Sequence Diagram - US318

== Configure the Show Proposal Template ==

activate crmManager

crmManager -> system : Request proposals ready for creation
activate system
system -> system : Get all proposals ready for creation

system -> crmManager : Provide proposals ready for creation
deactivate system


crmManager -> system : Provide a show Proposal to configure its Template
activate system

system ->system: Get all the show proposal templates

system -> crmManager : Request Show Proposal Template
deactivate system
crmManager -> system : Provide Show Proposal Template

activate system
system -> system : Update the show proposal template
system -> crmManager : Confirm configuration updated
deactivate system

@enduml
