@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Drone Tech" as droneTech
participant "System" as system

title System Sequence Diagram - US322

== List maintenance types ==
activate droneTech

droneTech -> system : Asks to list maintenance types
activate system

system --> droneTech : Sends a list of maintenance types
deactivate system

deactivate system



@enduml
