@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Manager" as crmManager
participant "System" as system

title System Sequence Diagram - US235

== List show requests of client ==
activate crmManager

crmManager -> system : Wants to list show request of client
activate system

system -> crmManager : Show list of Active Clients
deactivate system
crmManager -> system : Choose client

activate system

system -> crmManager : Show list of show requests \n related to the client
deactivate system



@enduml
