@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Drone Tech" as droneTech
participant "System" as system

title System Sequence Diagram - US243

== List drones in the inventory  ==
activate droneTech

droneTech -> system : Asks to list active drones from inventory
activate system

system -> droneTech : Shows list of active drones models in inventory
deactivate system
droneTech -> system : Selects drone model to list

activate system
system -> droneTech : Shows list of drone model selected





@enduml
