@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "System" as system

title System Sequence Diagram - US231

== Figure catalogue ==
    activate crmCollaborator

        crmCollaborator -> system : Asks to display all public figures in the catalogue
        activate system

            system -> crmCollaborator : Displays the public figures in the catalogue
        deactivate system


@enduml
