@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Show Designer" as showDesigner
participant "System" as system

title System Sequence Diagram - US248

== Inactive/Activate a Figure Category  ==
activate showDesigner

showDesigner -> system : Request list of figure categories
activate system

system -> showDesigner : Returns list of figure categories and their status
deactivate system

showDesigner -> system : Request to activate/deactivate a figure category
activate system
system -> system : Update figure category status
system -> showDesigner : Confirm figure category status updated
deactivate system




@enduml
