@startuml
title Sequence Diagram

actor "Show Designer" as Actor
participant "AddFigureCategoryUI" as UI <<presentation>>
participant "AddFigureCategoryController" as Controller <<application>>
participant "AuthorizationService" as AuthorizationService <<auth>>
participant "FigureCategoryManagementService" as FigureCategoryManagementService <<application>>
participant "FigureCategory" as FigureCategory <<domain>>
participant "FigureCategoryRepository" as FigureCategoryRepository <<repository>>
database "Database" as Database

activate Actor

Actor -> UI: show()
    activate UI

UI -> Controller** : create()

UI --> Actor: Request FigureCategory data (figureName, figureDescription)

deactivate UI

Actor -> UI: Insert FigureCategory data


    activate UI

        UI -> Controller : addFigureCategory(categoryName, categoryDescription)
            activate Controller

                Controller -> AuthorizationService** : ensureAuthenticatedUserHasAnyOf()

                deactivate AuthorizationService

                Controller -> FigureCategoryManagementService : registerNewFigureCategory(figureName, figureDescription);
                activate FigureCategoryManagementService


                    FigureCategoryManagementService -> FigureCategory : new FigureCategory(name, description, CurrentTimeCalendars.now())
                    activate FigureCategory

                        FigureCategory --> FigureCategoryManagementService
                    deactivate FigureCategory


                    FigureCategoryManagementService -> FigureCategoryRepository : save(newFigureCategory)

                    activate FigureCategoryRepository

                             FigureCategoryRepository -> Database : save()
                             activate Database

                                Database --> FigureCategoryRepository
                             deactivate Database

                             FigureCategoryRepository --> FigureCategoryManagementService
                    deactivate FigureCategoryRepository

                    FigureCategoryManagementService --> Controller
                deactivate FigureCategoryManagementService

                Controller --> UI
            deactivate Controller
        UI --> Actor : Inform operation success
        deactivate UI
deactivate Actor

@enduml
