@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Drone Tech" as droneTech
participant "System" as system

title System Sequence Diagram - US245

== Add figure category  ==
activate droneTech

droneTech -> system : Wants to add figure category to catalogue
activate system

system -> droneTech : Asks for figure category information(name, description)
deactivate system
droneTech -> system : Types in figure category information

activate system
system -> droneTech : Returns success message





@enduml
