@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Show Designer" as showDesigner
participant "System" as system

title System Sequence Diagram - US245

== Add figure category  ==
activate showDesigner

showDesigner -> system : Wants to add figure category to catalogue
activate system

system -> showDesigner : Asks for figure category information(name, description)
deactivate system

showDesigner -> system : Types in figure category information
activate system

system -> showDesigner : Returns success message
deactivate system





@enduml
