@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "SearchFigureAction" as ACTION
participant "SearchFigureUI" as UI
participant "SearchFigureController" as CTRL <<application>>
participant "AuthorizationService" as AuthorizationService <<auth>>
participant "FigureManagementService" as FigureManagementService <<application>>
participant "FigureRepository" as FigureRepository <<repository>>
database "Database" as Database

title Sequence Diagram - US232

activate crmCollaborator

    crmCollaborator -> ACTION : Asks to search a figure by category and/or keyword
    activate ACTION

        ACTION -> UI** : create
        deactivate ACTION
        activate UI

            UI -> crmCollaborator : Request data(category and/or keyword)
    deactivate UI
    crmCollaborator -> UI : Types category and/or keyword

    activate UI

        UI -> CTRL : ensureAuthenticatedUser()
        activate CTRL

            CTRL -> AuthorizationService** : ensureAuthenticatedUserHasAnyOf()
        deactivate CTRL

        alt Search figure only with keyword
        UI -> CTRL : findFiguresByKeyword(keyword)
        activate CTRL

            CTRL -> FigureManagementService : findFigure(keyword)
            activate FigureManagementService

                FigureManagementService -> FigureRepository : findByKeyword(keyword)
                activate FigureRepository

                    FigureRepository -> Database : findByKeyword(keyword)
                    activate Database

                        Database -> FigureRepository : figure
                    deactivate Database

                    FigureRepository -> FigureManagementService : figure
                deactivate FigureRepository

                FigureManagementService -> CTRL : figure
            deactivate FigureManagementService

            CTRL -> UI : figure
        deactivate CTRL

        else Search figure only with category
        UI -> CTRL : findFiguresByCategory(category)
        activate CTRL

            CTRL -> FigureManagementService : findByCategory(figureCategory)
            activate FigureManagementService

                FigureManagementService -> FigureRepository : findByFigureCategory(category)
                activate FigureRepository

                    FigureRepository -> Database : findByFigureCategory(category)
                    activate Database

                        Database -> FigureRepository : figure
                    deactivate Database

                    FigureRepository -> FigureManagementService : figure
                deactivate FigureRepository

                FigureManagementService -> CTRL : figure
            deactivate FigureManagementService

            CTRL -> UI : figure
        deactivate CTRL

        else Search figure with keyword and category
        UI -> CTRL : findFiguresByKeywordAndCategory(keyword, category)
        activate CTRL

            CTRL -> FigureManagementService : findByKeywordAndCategory(keyword, category)
            activate FigureManagementService

                FigureManagementService -> FigureRepository : findByKeywordAndCategory(keyword, category)
                activate FigureRepository

                    FigureRepository -> Database : findByKeywordAndCategory(keyword, category)
                    activate Database

                        Database -> FigureRepository : figure
                    deactivate Database

                    FigureRepository -> FigureManagementService : figure
                deactivate FigureRepository

                FigureManagementService -> CTRL : figure
            deactivate FigureManagementService

            CTRL -> UI : figure
        deactivate CTRL

        end
        UI -> crmCollaborator : Displays the search results of the figure \nand displays operation success
    deactivate UI



@enduml
