@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "System" as system

title System Sequence Diagram - US232

== Search figure catalogue ==
activate crmCollaborator

    crmCollaborator -> system : Asks to search a figure by category and/or keyword
    activate system

        system -> crmCollaborator : Request data(category and/or keyword)
    deactivate system
    crmCollaborator -> system : Types category and/or keyword

    activate system

        system -> crmCollaborator : Displays the search results of the figure \nand displays operation success
    deactivate system



@enduml
