@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Manager" as crmManager
participant "System" as system

title System Sequence Diagram - US234

== Decommission figure ==
activate crmManager

crmManager -> system : Wants to decommission a figure
activate system

system -> crmManager : Shows list of active figures in the catalogue
deactivate system
crmManager -> system : Choose the figure to decommission

activate system

system -> crmManager : Confirms Figure has been decommissioned
deactivate system



@enduml
