@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Manager" as crmManager
participant "System" as system

title System Sequence Diagram - US234

== Decommission figure ==
activate crmManager

crmManager -> system : Wants to decommission a figure
activate system

system -> crmManager : Show List of Active Figures
deactivate system
crmManager -> system : Choose Figure to Decommission

activate system

system -> crmManager : Confirms Figure has been decommissioned
deactivate system



@enduml
