@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Manager" as showDesigner
participant "System" as system

title System Sequence Diagram - US234

== Decommission figure ==
activate showDesigner

showDesigner -> system : Wants to decommission a figure
activate system

system -> showDesigner : Shows list of active figures in the catalogue
deactivate system
showDesigner -> system : Choose the figure to decommission

activate system

system -> showDesigner : Confirms Figure has been decommissioned
deactivate system



@enduml
