@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "RegisterShowProposalAction" as ACTION <<presentation>>
participant "RegisterShowProposalUI" as UI <<presentation>>
participant "RegisterShowProposalController" as CTRL <<application>>
participant "AuthorizationService" as AuthorizationService <<auth>>
participant "CustomerManagementService" as CustomerManagementService <<application>>
participant "ShowRequestManagementService" as ShowRequestManagementService <<application>>
participant "ShowProposalManagementService" as ShowProposalManagementService <<application>>
participant "TemplateManagementService" as TemplateManagementService <<application>>
participant "CustomerDTOParser" as CustomerDTOParser <<dto>>
participant "ShowRequestDTOParser" as ShowRequestDTOParser <<dto>>
participant "ShowProposal" as ShowProposal <<domain>>
participant "CustomerRepository" as CustomerRepository <<repository>>
participant "ShowRequestRepository" as ShowRequestRepository <<repository>>
participant "ShowProposalRepository" as ShowProposalRepository <<repository>>
participant "TemplateRepository" as TemplateRepository <<repository>>
database "Database" as Database

title Sequence Diagram - US230

 activate crmCollaborator

     crmCollaborator -> ACTION : Asks to start creating a show proposal
     activate ACTION

        ACTION -> UI** : create
        ACTION -> UI : show()
        deactivate ACTION

        activate UI

        UI -> CTRL**: create
        UI -> CTRL : listCustomers()
        activate CTRL

            CTRL -> AuthorizationService** : ensureAuthenticatedUserHasAnyOf(Roles.CRM_COLLABORATOR)
            CTRL -> CustomerManagementService : findAllActiveCustomers()
            activate CustomerManagementService

                CustomerManagementService -> CustomerRepository : findByActive(true)
                activate CustomerRepository

                    CustomerRepository -> Database : findByActive(true)
                    activate Database

                        Database -> CustomerRepository : customers
                    deactivate Database

                    CustomerRepository -> CustomerManagementService : customers
                deactivate CustomerRepository

                CustomerManagementService -> CTRL : customers
            deactivate CustomerManagementService

            CTRL -> CustomerDTOParser : transformToCustomerDTOList(customers)
            activate CustomerDTOParser

                CustomerDTOParser -> CTRL : customersDTO
            deactivate CustomerDTOParser

            CTRL -> UI : customersDTO
        deactivate CTRL
        UI -> crmCollaborator : displays the list of customers
     deactivate UI

     crmCollaborator -> UI : selects the customer
     activate UI

        UI -> CTRL : listShowRequests(customerDTO)
        activate CTRL

            CTRL -> CustomerDTOParser : getCustomerFromDTO(customerDTO)
            activate CustomerDTOParser

                CustomerDTOParser -> CTRL : customer
            deactivate CustomerDTOParser

            CTRL -> ShowRequestManagementService : findAllCustomerShowRequests(customer)
            activate ShowRequestManagementService

                ShowRequestManagementService -> ShowRequestRepository : findByCustomer(customer)
                activate ShowRequestRepository

                    ShowRequestRepository -> Database : findByCustomer(customer)
                    activate Database

                        Database -> ShowRequestRepository : showRequests
                    deactivate Database

                    ShowRequestRepository -> ShowRequestManagementService : showRequests
                deactivate ShowRequestRepository

                ShowRequestManagementService -> CTRL : showRequests
            deactivate ShowRequestManagementService

            CTRL -> ShowRequestDTOParser : transformToShowRequestDTOlist(showRequests)
            activate ShowRequestDTOParser

                ShowRequestDTOParser -> CTRL : showRequestDTO
            deactivate ShowRequestDTOParser

            CTRL -> UI : showRequestsDTO
        deactivate CTRL

        UI -> crmCollaborator : Displays the list of show request associated to the customer
     deactivate UI

     crmCollaborator -> UI : selects a show request
     activate UI

        UI -> CTRL : listTemplates()
        activate CTRL

            CTRL -> TemplateManagementService : listAllTemplates()
            activate TemplateManagementService

                TemplateManagementService -> TemplateRepository : findAll()
                activate TemplateRepository

                    TemplateRepository -> Database : findAll()
                    activate Database

                        Database -> TemplateRepository : templates
                    deactivate Database

                    TemplateRepository -> TemplateManagementService : template
                deactivate TemplateRepository

                TemplateManagementService -> CTRL : templates
            deactivate TemplateManagementService

            CTRL -> UI : templates
        deactivate CTRL

        UI -> crmCollaborator : displays current show proposal templates
     deactivate UI

     crmCollaborator -> UI : selects a template
     activate UI

         UI -> crmCollaborator : displays the current attributes of the show request(location, date, time, duration, \ntotal number of drones) and asks the user if he wants to change the attribute(s)
     deactivate UI

     crmCollaborator -> UI : selects the attribute he wants to change or selects the option to don't change any attribute
     alt If the user wants to change the attributes displayed
     activate UI

        UI -> crmCollaborator : request the data of the attribute
     deactivate UI

     crmCollaborator -> UI : types requested data
     activate UI

        end
        UI -> CTRL : registerShowProposal(showRequestDTO, location, date, time, duration, totalNumberOfDrones, insurance)
        activate CTRL

            CTRL -> ShowRequestDTOParser : getShowRequestfromDTO(showRequestDTO)
            activate ShowRequestDTOParser

                ShowRequestDTOParser -> CTRL : showRequest
            deactivate ShowRequestDTOParser

            CTRL -> ShowProposalManagementService : registerShowProposal(showRequest, location, date, time, duration, totalNumberOfDrones, insurance)
            activate ShowProposalManagementService

                ShowProposalManagementService -> ShowProposal : new ShowProposal(showRequest, location, date, time, duration, totalNumberOfDrones, insurance)
                activate ShowProposal

                    ShowProposal -> ShowProposalManagementService : new ShowProposal
                deactivate ShowProposal

                ShowProposalManagementService -> ShowProposalRepository : save(showProposal)
                activate ShowProposalRepository

                    ShowProposalRepository -> Database : save()
                    activate Database

                        Database --> ShowProposalRepository :
                    deactivate Database

                    ShowProposalRepository --> ShowProposalManagementService :
                deactivate ShowProposalRepository
                ShowProposalManagementService --> CTRL :
            deactivate ShowProposalManagementService

            CTRL --> UI :
        deactivate CTRL

        UI -> crmCollaborator :  displays operation success
     deactivate UI
 @enduml