@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "RegisterShowProposalAction" as ACTION <<presentation>>
participant "RegisterShowProposalUI" as UI <<presentation>>
participant "RegisterShowProposalController" as CTRL <<application>>
participant "AuthorizationService" as AuthorizationService <<auth>>
participant "CustomerManagementService" as CustomerManagementService <<application>>
participant "ShowRequestManagementService" as ShowRequestManagementService <<application>>
participant "ShowProposalManagementService" as ShowProposalManagementService <<application>>
participant "ShowProposal" as ShowProposal <<domain>>
participant "CustomerRepository" as CustomerRepository <<repository>>
participant "ShowRequestRepository" as ShowRequestRepository <<repository>>
participant "ShowProposalRepository" as ShowProposalRepository <<repository>>
database "Database" as Database

title Sequence Diagram - US230

 activate crmCollaborator

     crmCollaborator -> ACTION : Asks to start creating a show proposal
     activate ACTION

        ACTION -> UI** : create
        ACTION -> UI : show()
        deactivate ACTION

        activate UI

        UI -> CTRL**: create
        UI -> CTRL : listCustomers()
        activate CTRL

            CTRL -> AuthorizationService** : ensureAuthenticatedUserHasAnyOf(Roles.CRM_COLLABORATOR)
            CTRL -> CustomerManagementService : findAllActiveCustomers()
            activate CustomerManagementService

                CustomerManagementService -> CustomerRepository : findByActive(true)
                activate CustomerRepository

                    CustomerRepository -> Database : findByActive(true)
                    activate Database

                        Database -> CustomerRepository : listOfActiveClients
                    deactivate Database

                    CustomerRepository -> CustomerManagementService : listOfActiveClients
                deactivate CustomerRepository

                CustomerManagementService -> CTRL : listOfActiveClients
            deactivate CustomerManagementService

            CTRL -> UI : listOfActiveClients
        deactivate CTRL
        UI -> crmCollaborator : displays the list of customers
     deactivate UI

     crmCollaborator -> UI : selects the customer
     activate UI

        UI -> CTRL : listShowRequests(customer)
        activate CTRL

            CTRL -> ShowRequestManagementService : findAllCustomerShowRequests(customer)
            activate ShowRequestManagementService

                ShowRequestManagementService -> ShowRequestRepository : findByCustomer(customer)
                activate ShowRequestRepository

                    ShowRequestRepository -> Database : findByCustomer(customer)
                    activate Database

                        Database -> ShowRequestRepository : listOfShowRequests
                    deactivate Database

                    ShowRequestRepository -> ShowRequestManagementService : listOfShowRequests
                deactivate ShowRequestRepository

                ShowRequestManagementService -> CTRL : listOfShowRequests
            deactivate ShowRequestManagementService

            CTRL -> UI : listOfShowRequests
        deactivate CTRL

        UI -> crmCollaborator : Displays the list of show request associated to the customer
     deactivate UI

     crmCollaborator -> UI : selects a show request
     activate UI

         UI -> crmCollaborator : displays the current attributes of the show request(location, date, time, duration, \ntotal number of drones) and asks the user if he wants to change the attribute(s)
     deactivate UI

     crmCollaborator -> UI : selects the attribute he wants to change or selects the option to don't change any attribute
     alt If the user wants to change the attributes displayed
     activate UI

        UI -> crmCollaborator : request the data of the attribute
     deactivate UI

     crmCollaborator -> UI : types requested data
     activate UI

        end
        UI -> CTRL : registerShowProposal(showRequest, location, date, time, duration, totalNumberOfDrones)
        activate CTRL

            CTRL -> ShowProposalManagementService : registerShowProposal(showRequest, location, date, time, duration, totalNumberOfDrones)
            activate ShowProposalManagementService

                ShowProposalManagementService -> ShowProposal : new ShowProposal(showRequest, location, date, time, duration, totalNumberOfDrones)
                activate ShowProposal

                    ShowProposal -> ShowProposalManagementService : new ShowProposal
                deactivate ShowProposal

                ShowProposalManagementService -> ShowProposalRepository : save(showProposal)
                activate ShowProposalRepository

                    ShowProposalRepository -> Database : save()
                    activate Database

                        Database --> ShowProposalRepository :
                    deactivate Database

                    ShowProposalRepository --> ShowProposalManagementService :
                deactivate ShowProposalRepository
                ShowProposalManagementService --> CTRL :
            deactivate ShowProposalManagementService

            CTRL --> UI :
        deactivate CTRL

        UI -> crmCollaborator :  displays operation success
     deactivate UI
 @enduml