@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "CRM Collaborator" as crmCollaborator
participant "System" as system

title System Sequence Diagram - US310

== Create Show Proposal ==
activate crmCollaborator

    crmCollaborator -> system : Asks to start creating a show proposal
    activate system

        system -> crmCollaborator : displays the list of customers
    deactivate system

    crmCollaborator -> system : selects the costumer
    activate system

        system -> crmCollaborator : Displays the list of show request associated to the customer
    deactivate system

    crmCollaborator -> system : selects a show request
    activate system

        system -> crmCollaborator : displays current show proposal templates
    deactivate system

    crmCollaborator -> system : selects a template
    activate system

         system -> crmCollaborator : displays the current attributes of the show request(location, date, time, duration, \ntotal number of drones) and asks the user if he wants to change the attribute(s)
    deactivate system

    crmCollaborator -> system : selects the attribute he wants to change or selects the option to don't change any attribute
    alt If the user wants to change the attributes displayed
    activate system

         system -> crmCollaborator : request the data of the attribute
    deactivate system

    crmCollaborator -> system : types requested data
    activate system

        end
        system -> crmCollaborator :  displays operation success
    deactivate system

@enduml
