@startuml

class CreateCustomerUI {

}

class CreateCustomerController {
+CreateCustomerController();
+createCustomer(vatNumber,address,phoneNumber,email,name,clientStatus,password);
}

class Customer {

}

CreateCustomerUI -> CreateCustomerController
CreateCustomerController -> Customer

@enduml