@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Show Designer" as showDesigner
participant "System" as system

title System Sequence Diagram - US233

== Add figure to the catalogue ==
activate showDesigner

showDesigner -> system : Add figure to the catalogue
activate system

system -> showDesigner : Request Figure Information ("Description, Keywords, Category")
deactivate system
showDesigner -> system : Provide Figure Information

activate system

system -> showDesigner : Confirm Figure Added
deactivate system



@enduml
